"""add bookmakers to enriched_snapshots

Revision ID: 02f4bf42e179
Revises: aa04ff78e30f
Create Date: 2026-03-04 20:32:01.117009

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '02f4bf42e179'
down_revision: str | Sequence[str] | None = 'aa04ff78e30f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enriched_snapshots', sa.Column('bookmakers', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enriched_snapshots', 'bookmakers')
    # ### end Alembic commands ###
