"""initial schema

Revision ID: 218ef530bb5e
Revises: 
Create Date: 2026-03-03 19:12:27.997543

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '218ef530bb5e'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('credits_used', sa.Integer(), nullable=False),
    sa.Column('credits_remaining', sa.Integer(), nullable=False),
    sa.Column('sport_key', sa.String(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_usage_recorded_at', 'api_usage', ['recorded_at'], unique=False)
    op.create_table('bookmaker_odds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('bookmaker_key', sa.String(), nullable=False),
    sa.Column('market_key', sa.String(), nullable=False),
    sa.Column('outcome_name', sa.String(), nullable=False),
    sa.Column('outcome_price', sa.Float(), nullable=False),
    sa.Column('outcome_point', sa.Float(), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bookmaker_odds_bookmaker_market', 'bookmaker_odds', ['bookmaker_key', 'market_key'], unique=False)
    op.create_index('ix_bookmaker_odds_snapshot_id', 'bookmaker_odds', ['snapshot_id'], unique=False)
    op.create_index('ix_bookmaker_odds_snapshot_market_bookmaker', 'bookmaker_odds', ['snapshot_id', 'market_key', 'bookmaker_key'], unique=False)
    op.create_table('enriched_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('best_line', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('consensus_line', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('vig_free', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('movement', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id')
    )
    op.create_index('ix_enriched_snapshots_event_id_computed_at', 'enriched_snapshots', ['event_id', 'computed_at'], unique=False)
    op.create_index('ix_enriched_snapshots_snapshot_id', 'enriched_snapshots', ['snapshot_id'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('sport_key', sa.String(), nullable=False),
    sa.Column('sport_group', sa.String(), nullable=False),
    sa.Column('home_team', sa.String(), nullable=False),
    sa.Column('away_team', sa.String(), nullable=False),
    sa.Column('commence_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index('ix_events_external_id', 'events', ['external_id'], unique=True)
    op.create_index('ix_events_sport_group', 'events', ['sport_group'], unique=False)
    op.create_index('ix_events_sport_key_commence_time', 'events', ['sport_key', 'commence_time'], unique=False)
    op.create_index('ix_events_status_commence_time', 'events', ['status', 'commence_time'], unique=False)
    op.create_table('odds_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('credits_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_odds_snapshots_event_id_fetched_at', 'odds_snapshots', ['event_id', 'fetched_at'], unique=False)
    op.create_index('ix_odds_snapshots_fetched_at', 'odds_snapshots', ['fetched_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_odds_snapshots_fetched_at', table_name='odds_snapshots')
    op.drop_index('ix_odds_snapshots_event_id_fetched_at', table_name='odds_snapshots')
    op.drop_table('odds_snapshots')
    op.drop_index('ix_events_status_commence_time', table_name='events')
    op.drop_index('ix_events_sport_key_commence_time', table_name='events')
    op.drop_index('ix_events_sport_group', table_name='events')
    op.drop_index('ix_events_external_id', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_enriched_snapshots_snapshot_id', table_name='enriched_snapshots')
    op.drop_index('ix_enriched_snapshots_event_id_computed_at', table_name='enriched_snapshots')
    op.drop_table('enriched_snapshots')
    op.drop_index('ix_bookmaker_odds_snapshot_market_bookmaker', table_name='bookmaker_odds')
    op.drop_index('ix_bookmaker_odds_snapshot_id', table_name='bookmaker_odds')
    op.drop_index('ix_bookmaker_odds_bookmaker_market', table_name='bookmaker_odds')
    op.drop_table('bookmaker_odds')
    op.drop_index('ix_api_usage_recorded_at', table_name='api_usage')
    op.drop_table('api_usage')
    # ### end Alembic commands ###
